# Generated by Django 5.1.1 on 2024-09-26 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_comment_likes_remove_blog_likes_blog_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyBlog',
            fields=[
                ('blog_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.blog')),
                ('special_field', models.CharField(blank=True, max_length=100, null=True)),
            ],
            bases=('blog.blog',),
        ),
        migrations.AddField(
            model_name='blog',
            name='parent_blog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_blogs', to='blog.blog'),
        ),
    ]
